# Site settings
title: www.juliangiesen.de
email: info@juliangiesen.de
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
copyright: 2016
baseurl: /

name: Julian Giesen

twitter_username: jugisan
github_username: jugisan
xing_name: Julian_Giesen2
linkedin_name: juliangiesen

# Build settings
timezone: Europe/Berlin
highlighter: rouge
markdown: kramdown
